# Generated by Django 5.0.7 on 2024-07-20 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Author name can only contain letters, spaces, hyphens, apostrophes, and periods.', regex="^[a-zA-Z\\s\\-\\'\\.]+$")])),
                ('joke', models.CharField(max_length=300)),
            ],
        ),
    ]
